# Generated by Django 4.1.2 on 2022-10-06 21:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=50, null=True)),
                ('reminder_time', models.CharField(choices=[('morning', 'morning'), ('noon', 'noon'), ('evening', 'evening'), ('night', 'night')], max_length=7, null=True)),
                ('frequency', models.PositiveIntegerField(null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, null=True)),
                ('last_name', models.CharField(max_length=25, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('other', 'other')], max_length=5, null=True)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('password', models.IntegerField(null=True)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('profile_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment_date', models.DateTimeField(null=True)),
                ('reminder_status', models.CharField(choices=[('missed', 'missed'), ('seen', 'seen'), ('snooze', 'snooze')], max_length=7, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_recepient', to='caremark.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ImageVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_image', models.ImageField(upload_to='')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_id_patient', to='caremark.patient')),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_image', to='caremark.reminder')),
            ],
        ),
    ]
