# Generated by Django 4.1.2 on 2022-10-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caremark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_of_kin',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number_Next_of_kin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'other')], max_length=8, null=True),
        ),
    ]
