# Generated by Django 4.1.2 on 2022-10-07 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caremark', '0003_patient_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='profile_image',
        ),
    ]
